# Dựa trên image cơ bản nào
FROM python:3

# Khai báo thư mục làm việc
WORKDIR C:\Users\ADMIN\DockerPy

# Copy toàn bộ file mã nguồn và các file khác vào image
COPY . .

# Thực hiện lệnh chạy
CMD ["python","./Dpy.py"]